name: "Deploy prosit 1"

on: 
  push: 
    tags: 
      - "prosit1/v*"

env:
  PROJECT_PATH: prosit1/prosit1.csproj

jobs: 
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.x
      - run: dotnet restore 
      - run: dotnet build -c Release --no-restore
<<<<<<< HEAD
      - run: dotnet publish -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true
=======
      - run: dotnet publish -c Release --self-contained -r win-x64 -p:PublishSingleFile=true --no-build
>>>>>>> efb093c1961bd36d0ef58fb2ca767a412145696a

